### PR TITLE
Lightweight main image

### PR DESCRIPTION
**Pull request by itaibo**
Hi!

I noticed the web page load time was very high due to the main image, which is 12.7 MB

In order to optimize the load time and make the website accessible to people with limited data plans, I created a lightweight image from the original. The weight is 562 KB and size is 740x988 px (double the display size, to have high quality in retina screens)

### CODE REVIEW

**Comment by jdubois** [comment]
@itaibo you are optimizing my own image on my personal website? Wow! Well, thanks a lot!!

**Comment by itaibo** [comment]
You are welcome! Was a quick improvement with high impact in the page optimization :)

**Comment by jdubois** [comment]
If you're looking for more interesting OSS work to do (honestly, who cares about my webpage?), you can have a look at @jhipster - you'll have much more impact, for tons of people!

**Comment by itaibo** [comment]
Okay! I will take a look at @jhipster! Thank you!

**Pull request merged**
